import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // contentSidebar: [{ type: "autogenerated", dirName: "." }],

  // But you can create a sidebar manually

  contentSidebar: [
    // "introduction",
    // "overview",
    {
      type: "category",
      link: {
        type: "generated-index",
      },
      collapsed: false,
      label: "Introduction",
      items: ["introduction/overview", "introduction/glossary"],
    },
    {
      type: "category",
      link: {
        type: "doc",
        id: "getting-started/getting-started-intro",
        // keywords: ["setup"],
      },
      collapsed: false,
      label: "Getting Started",
      items: [
        // "getting-started/getting-started", // Main page (can be omitted if it's linked above)
        "getting-started/install-dependencies",
        "getting-started/launch-local-node",
        "getting-started/system-requirements",
        "getting-started/create-development-wallet",
        "getting-started/create-development-accounts",
      ],
    },
    {
      type: "category",
      link: {
        type: "doc",
        id: "smart-contract-development/smart-contract-development-intro",
      },
      label: "Smart Contract Development",
      collapsed: false,
      items: [
        "smart-contract-development/smart-contract-basics",
        "smart-contract-development/block-explorer",
        "smart-contract-development/hello-world-contract-short",
        "smart-contract-development/company-contract",
        {
          type: "category",
          label: "Interacting with Contracts",
          link: {
            type: "generated-index",
          },
          collapsed: false,
          items: [
            {
              type: "autogenerated",
              dirName: "smart-contract-development/interacting-with-contracts",
            },
          ],
        },
      ],
    },

    {
      type: "category",
      link: {
        type: "generated-index",
        // TODO - verify that's okay
        description: `Source Acknowledgment: The content in the following sections has been sourced from the official EOSIO GitHub repository - https://github.com/EOSIO/eos. This material is utilized under the terms of its open source license.`,
        // id: "api-reference/api-reference-intro",
        // keywords: ["setup"],
      },
      collapsed: true,
      label: "API Reference",
      items: [
        {
          type: "category",
          label: "cleos",
          link: {
            type: "doc",
            id: "api-reference/tooling/cleos/index",
          },
          items: [
            {
              type: "category",
              label: "Command Reference",
              link: {
                type: "doc",
                id: "api-reference/tooling/cleos/command-reference/index",
              },
              items: [
                {
                  type: "category",
                  label: "convert",
                  link: {
                    type: "doc",
                    id: "api-reference/tooling/cleos/command-reference/convert/index",
                  },
                  items: [
                    "api-reference/tooling/cleos/command-reference/convert/pack-action-data",
                    "api-reference/tooling/cleos/command-reference/convert/pack-transaction",
                    "api-reference/tooling/cleos/command-reference/convert/unpack-action-data",
                    "api-reference/tooling/cleos/command-reference/convert/unpack-transaction",
                  ],
                },
                {
                  type: "category",
                  label: "create",
                  link: {
                    type: "doc",
                    id: "api-reference/tooling/cleos/command-reference/create/index",
                  },
                  items: [
                    "api-reference/tooling/cleos/command-reference/create/account",
                    "api-reference/tooling/cleos/command-reference/create/key",
                  ],
                },
                {
                  type: "category",
                  label: "get",
                  link: {
                    type: "doc",
                    id: "api-reference/tooling/cleos/command-reference/get/index",
                  },
                  items: [
                    "api-reference/tooling/cleos/command-reference/get/abi",
                    "api-reference/tooling/cleos/command-reference/get/account",
                    "api-reference/tooling/cleos/command-reference/get/accounts",
                    "api-reference/tooling/cleos/command-reference/get/actions",
                    "api-reference/tooling/cleos/command-reference/get/block",
                    "api-reference/tooling/cleos/command-reference/get/code",
                    "api-reference/tooling/cleos/command-reference/get/currency-balance",
                    "api-reference/tooling/cleos/command-reference/get/currency-stats",
                    // 'api-reference/tooling/cleos/command-reference/get/currency',
                    "api-reference/tooling/cleos/command-reference/get/info",
                    "api-reference/tooling/cleos/command-reference/get/kv-table",
                    "api-reference/tooling/cleos/command-reference/get/schedule",
                    "api-reference/tooling/cleos/command-reference/get/scope",
                    "api-reference/tooling/cleos/command-reference/get/servants",
                    "api-reference/tooling/cleos/command-reference/get/table",
                    "api-reference/tooling/cleos/command-reference/get/transaction-id",
                    "api-reference/tooling/cleos/command-reference/get/transaction",
                  ],
                },
                {
                  type: "category",
                  label: "multisig",
                  link: {
                    type: "doc",
                    id: "api-reference/tooling/cleos/command-reference/multisig/index",
                  },
                  items: [
                    "api-reference/tooling/cleos/command-reference/multisig/multisig-approve",
                    "api-reference/tooling/cleos/command-reference/multisig/multisig-cancel",
                    "api-reference/tooling/cleos/command-reference/multisig/multisig-exec",
                    "api-reference/tooling/cleos/command-reference/multisig/multisig-invalidate",
                    "api-reference/tooling/cleos/command-reference/multisig/multisig-propose-trx",
                    "api-reference/tooling/cleos/command-reference/multisig/multisig-propose",
                    "api-reference/tooling/cleos/command-reference/multisig/multisig-review",
                    "api-reference/tooling/cleos/command-reference/multisig/multisig-unapprove",
                  ],
                },
                {
                  type: "category",
                  label: "net",
                  link: {
                    type: "doc",
                    id: "api-reference/tooling/cleos/command-reference/net/index",
                  },
                  items: [
                    "api-reference/tooling/cleos/command-reference/net/connect",
                    "api-reference/tooling/cleos/command-reference/net/disconnect",
                    "api-reference/tooling/cleos/command-reference/net/peers",
                    "api-reference/tooling/cleos/command-reference/net/status",
                  ],
                },
                {
                  type: "category",
                  label: "push",
                  link: {
                    type: "doc",
                    id: "api-reference/tooling/cleos/command-reference/push/index",
                  },
                  items: [
                    "api-reference/tooling/cleos/command-reference/push/push-action",
                    "api-reference/tooling/cleos/command-reference/push/push-transaction",
                    "api-reference/tooling/cleos/command-reference/push/push-transactions",
                  ],
                },
                {
                  type: "category",
                  label: "set",
                  link: {
                    type: "doc",
                    id: "api-reference/tooling/cleos/command-reference/set/index",
                  },
                  items: [
                    "api-reference/tooling/cleos/command-reference/set/set-abi",
                    "api-reference/tooling/cleos/command-reference/set/set-account",
                    "api-reference/tooling/cleos/command-reference/set/set-action",
                    "api-reference/tooling/cleos/command-reference/set/set-code",
                    "api-reference/tooling/cleos/command-reference/set/set-contract",
                  ],
                },
                {
                  type: "category",
                  label: "system",
                  link: {
                    type: "doc",
                    id: "api-reference/tooling/cleos/command-reference/system/index",
                  },
                  items: [
                    "api-reference/tooling/cleos/command-reference/system/system-bidname",
                    "api-reference/tooling/cleos/command-reference/system/system-bidname",
                    "api-reference/tooling/cleos/command-reference/system/system-bidnameinfo",
                    "api-reference/tooling/cleos/command-reference/system/system-buyram",
                    "api-reference/tooling/cleos/command-reference/system/system-canceldelay",
                    "api-reference/tooling/cleos/command-reference/system/system-claimrewards",
                    "api-reference/tooling/cleos/command-reference/system/system-delegatebw",
                    "api-reference/tooling/cleos/command-reference/system/system-listbw",
                    "api-reference/tooling/cleos/command-reference/system/system-listproducers",
                    "api-reference/tooling/cleos/command-reference/system/system-newaccount",
                    "api-reference/tooling/cleos/command-reference/system/system-regproducer",
                    "api-reference/tooling/cleos/command-reference/system/system-regproxy",
                    // "api-reference/tooling/cleos/command-reference/system/system-rex-buyrex",
                    // "api-reference/tooling/cleos/command-reference/system/system-rex-cancelrexorder",
                    // "api-reference/tooling/cleos/command-reference/system/system-rex-closerex",
                    // "api-reference/tooling/cleos/command-reference/system/system-rex-consolidate",
                    // "api-reference/tooling/cleos/command-reference/system/system-rex-defundcpuloan",
                    // "api-reference/tooling/cleos/command-reference/system/system-rex-defundnetloan",
                    // "api-reference/tooling/cleos/command-reference/system/system-rex-deposit",
                    // "api-reference/tooling/cleos/command-reference/system/system-rex-fundcpuloan",
                    // "api-reference/tooling/cleos/command-reference/system/system-rex-fundnetloan",
                    // "api-reference/tooling/cleos/command-reference/system/system-rex-lendrex",
                    // "api-reference/tooling/cleos/command-reference/system/system-rex-mvfromsavings",
                    // "api-reference/tooling/cleos/command-reference/system/system-rex-mvtosavings",
                    // "api-reference/tooling/cleos/command-reference/system/system-rex-rentcpu",
                    // "api-reference/tooling/cleos/command-reference/system/system-rex-rentnet",
                    // "api-reference/tooling/cleos/command-reference/system/system-rex-rexexec",
                    // "api-reference/tooling/cleos/command-reference/system/system-rex-sellrex",
                    // "api-reference/tooling/cleos/command-reference/system/system-rex-unstaketorex",
                    // "api-reference/tooling/cleos/command-reference/system/system-rex-updaterex",
                    // "api-reference/tooling/cleos/command-reference/system/system-rex-withdraw",
                    // "api-reference/tooling/cleos/command-reference/system/system-rex",
                    "api-reference/tooling/cleos/command-reference/system/system-sellram",
                    "api-reference/tooling/cleos/command-reference/system/system-undelegatebw",
                    "api-reference/tooling/cleos/command-reference/system/system-unregprod",
                    "api-reference/tooling/cleos/command-reference/system/system-unregproxy",
                    {
                      type: "category",
                      label: "system voteproducer",
                      link: {
                        type: "doc",
                        id: "api-reference/tooling/cleos/command-reference/system/system-voteproducer",
                      },
                      items: [
                        "api-reference/tooling/cleos/command-reference/system/system-voteproducer-approve",
                        "api-reference/tooling/cleos/command-reference/system/system-voteproducer-prods",
                        "api-reference/tooling/cleos/command-reference/system/system-voteproducer-proxy",
                        "api-reference/tooling/cleos/command-reference/system/system-voteproducer-unapprove",
                      ],
                    },
                  ],
                },
                {
                  type: "category",
                  label: "validate",
                  link: {
                    type: "doc",
                    id: "api-reference/tooling/cleos/command-reference/validate/index",
                  },
                  items: [
                    "api-reference/tooling/cleos/command-reference/validate/validate-signatures",
                  ],
                },
                {
                  type: "category",
                  label: "version",
                  link: {
                    type: "doc",
                    id: "api-reference/tooling/cleos/command-reference/version/index",
                  },
                  items: [
                    "api-reference/tooling/cleos/command-reference/version/client",
                  ],
                },
                {
                  type: "category",
                  label: "wallet",
                  link: {
                    type: "doc",
                    id: "api-reference/tooling/cleos/command-reference/wallet/index",
                  },
                  items: [
                    "api-reference/tooling/cleos/command-reference/wallet/create",
                    "api-reference/tooling/cleos/command-reference/wallet/create-key",
                    "api-reference/tooling/cleos/command-reference/wallet/import",
                    "api-reference/tooling/cleos/command-reference/wallet/index",
                    "api-reference/tooling/cleos/command-reference/wallet/keys",
                    "api-reference/tooling/cleos/command-reference/wallet/list",
                    "api-reference/tooling/cleos/command-reference/wallet/lock",
                    "api-reference/tooling/cleos/command-reference/wallet/lock-all",
                    "api-reference/tooling/cleos/command-reference/wallet/open",
                    "api-reference/tooling/cleos/command-reference/wallet/private-keys",
                    "api-reference/tooling/cleos/command-reference/wallet/unlock",
                  ],
                },
                "api-reference/tooling/cleos/command-reference/sign",
                "api-reference/tooling/cleos/command-reference/transfer",
              ],
            },
            {
              type: "category",
              label: "how to",
              items: [
                "api-reference/tooling/cleos/how-to-guides/how-to-submit-a-transaction",
              ],
            },
          ],
        },
        {
          type: "category",
          label: "keosd",
          link: {
            type: "doc",
            id: "api-reference/tooling/keosd/index",
          },
          items: [
            "api-reference/tooling/keosd/usage",
            {
              type: "category",
              label: "Plugins",
              link: {
                type: "doc",
                id: "api-reference/tooling/keosd/plugins/index",
              },
              items: [
                "api-reference/tooling/keosd/plugins/wallet-api-plugin",
                "api-reference/tooling/keosd/plugins/wallet-plugin",
              ],
            },
            // "api-reference/tooling/keosd/security",
            "api-reference/tooling/keosd/wallet-specification",
            "api-reference/tooling/keosd/troubleshooting",
            "api-reference/tooling/keosd/faq",
          ],
        },
        {
          type: "category",
          label: "nodeos",
          link: {
            type: "doc",
            id: "api-reference/tooling/nodeos/index",
          },
          items: [
            "api-reference/tooling/nodeos/nodeos-apis",
            {
              type: "category",
              label: "Concepts",
              link: {
                type: "doc",
                id: "api-reference/tooling/nodeos/concepts/index",
              },
              items: [
                "api-reference/tooling/nodeos/concepts/context-free-data",
                "api-reference/tooling/nodeos/concepts/storage-and-read-modes",
              ],
            },
            {
              type: "category",
              label: "Plugins",
              items: [
                // "api-reference/tooling/nodeos/plugins/block-producing-explained",
                "api-reference/tooling/nodeos/plugins/blockvault-client-plugin",
                "api-reference/tooling/nodeos/plugins/chain-api-plugin",
                "api-reference/tooling/nodeos/plugins/chain-plugin",
                "api-reference/tooling/nodeos/plugins/db-size-api-plugin",
                "api-reference/tooling/nodeos/plugins/history-api-plugin",
                "api-reference/tooling/nodeos/plugins/history-plugin",
                "api-reference/tooling/nodeos/plugins/http-client-plugin",
                "api-reference/tooling/nodeos/plugins/http-plugin",
                "api-reference/tooling/nodeos/plugins/login-plugin",
                "api-reference/tooling/nodeos/plugins/net-api-plugin",
                "api-reference/tooling/nodeos/plugins/net-plugin",
                "api-reference/tooling/nodeos/plugins/producer-api-plugin",
                "api-reference/tooling/nodeos/plugins/producer-plugin",
                "api-reference/tooling/nodeos/plugins/resource-monitor-plugin",
                "api-reference/tooling/nodeos/plugins/state-history-plugin",
                "api-reference/tooling/nodeos/plugins/trace-api-plugin",
                "api-reference/tooling/nodeos/plugins/txn-test-gen-plugin",
              ],
            },
            {
              type: "category",
              label: "Logging",
              link: {
                type: "doc",
                id: "api-reference/tooling/nodeos/logging/index",
              },
              items: [
                {
                  type: "category",
                  label: "Native Logging",
                  link: {
                    type: "doc",
                    id: "api-reference/tooling/nodeos/logging/native-logging/index",
                  },
                  items: [
                    "api-reference/tooling/nodeos/logging/native-logging/setup-logging.json",
                    "api-reference/tooling/nodeos/logging/native-logging/logging-levels",
                  ],
                },
                {
                  type: "category",
                  label: "Third-Party Logging",
                  link: {
                    type: "doc",
                    id: "api-reference/tooling/nodeos/logging/third-party-logging/index",
                  },
                  items: [
                    "api-reference/tooling/nodeos/logging/third-party-logging/deep-mind-logger",
                  ],
                },
              ],
            },
            "api-reference/tooling/nodeos/replays",
            {
              type: "category",
              label: "How-To",
              items: [
                "api-reference/tooling/nodeos/how-to/how-to-configure-state-storage",
                "api-reference/tooling/nodeos/how-to/how-to-create-snapshot-with-full-history",
                "api-reference/tooling/nodeos/how-to/how-to-fast-start-without-old-history",
                "api-reference/tooling/nodeos/how-to/how-to-generate-a-blocks.log",
                "api-reference/tooling/nodeos/how-to/how-to-generate-a-snapshot",
                "api-reference/tooling/nodeos/how-to/how-to-replay-from-a-blocks.log",
                "api-reference/tooling/nodeos/how-to/how-to-replay-from-a-snapshot",
                "api-reference/tooling/nodeos/how-to/how-to-replay-or-resync-with-full-history",
                "api-reference/tooling/nodeos/how-to/how-to-restore-snapshot-with-full-history",
              ],
            },
            // "api-reference/tooling/nodeos/rpc-apis",
            "api-reference/tooling/nodeos/troubleshooting",
            // "api-reference/tooling/nodeos/usage",
          ],
        },
        {
          type: "category",
          label: "Utilities",
          link: {
            type: "doc",
            id: "api-reference/tooling/utilities/index",
          },
          items: [
            "api-reference/tooling/utilities/eosio-blocklog",
            "api-reference/tooling/utilities/trace-api-util",
          ],
        },
      ],
    },
  ],
};

export default sidebars;
