import type { SidebarsConfig } from "@docusaurus/plugin-content-docs";

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // contentSidebar: [{ type: "autogenerated", dirName: "." }],

  // But you can create a sidebar manually

  contentSidebar: [
    {
      type: "category",
      link: {
        type: "generated-index",
      },
      collapsed: false,
      label: "Wire Basics",
      items: [
        "introduction/overview",
        "introduction/wns-overview",
        // "introduction/wns-trx-flow",
        // "introduction/deposits",
        "introduction/glossary",
        "introduction/network-information",
      ],
    },

    {
      type: "category",
      link: {
        type: "doc",
        id: "getting-started/getting-started-intro",
      },
      collapsed: false,
      label: "Getting Started",
      items: [
        "getting-started/core-components",
        "getting-started/install-dependencies",
        "getting-started/manage-local-wallet-with-clio",
        "getting-started/create-development-accounts",
      ],
    },
    {
      type: "category",
      link: {
        type: "doc",
        id: "smart-contract-development/smart-contract-development-intro",
      },
      label: "Smart Contract Development",
      collapsed: false,
      items: [
        "smart-contract-development/accounts-permissions",
        {
          type: "category",
          label: "Smart Contract Basics",
          link: {
            type: "doc",
            id: "smart-contract-development/smart-contract-basics",
          },
          collapsed: false,
          items: [
            "smart-contract-development/types",
            "smart-contract-development/actions",
            "smart-contract-development/state-data",
          ],
        },
        // "smart-contract-development/block-explorer",
        "smart-contract-development/hello-world-contract-short",
        "smart-contract-development/company-contract",
        {
          type: "category",
          label: "Interacting with Contracts",
          link: {
            type: "generated-index",
          },
          collapsed: false,
          items: [
            {
              type: "autogenerated",
              dirName: "smart-contract-development/interacting-with-contracts",
            },
          ],
        },
      ],
    },
    {
      type: "category",
      link: {
        type: "generated-index",
      },
      collapsed: false,
      label: "Wire Hub",
      items: [
        "wire-hub/connect-to-a-rpc",
        "wire-hub/inspect-transaction",
        "wire-hub/connect-a-wallet",
        "wire-hub/create-wire-testnet-account",
        "wire-hub/request-a-policy",
      ],
    },
  ],

  apiReferenceSidebar: [
    {
      type: "category",
      link: {
        type: "doc",
        id: "api-reference/quick-reference",
      },
      collapsible: false,
      label: "Quick Reference",
      items: [],
    },
    // {
    //   type: "category",
    //   label: "Producer",
    //   items: [
    //     "api-reference/producer/add-greylist-accounts",
    //     // "api-reference/producer/create-snapshot",
    //     // "api-reference/producer/get-account-ram-corrections",
    //     // "api-reference/producer/get-greylist",
    //     // "api-reference/producer/get-integrity-hash",
    //     // "api-reference/producer/get-runtime-options",
    //     // "api-reference/producer/get-supported-protocol-features",
    //     // "api-reference/producer/get-whitelist-blacklist",
    //     // "api-reference/producer/pause",
    //     // "api-reference/producer/paused",
    //     // // "api-reference/producer/info",
    //     // "api-reference/producer/remove-greylist-accounts",
    //     // "api-reference/producer/resume",
    //     // "api-reference/producer/schedule-protocol-feature-activations",
    //     // "api-reference/producer/set-whitelist-blacklist",
    //     // "api-reference/producer/update-runtime-options",
    //   ],
    // },
    {
      type: "category",
      link: {
        type: "doc",
        id: "api-reference/tooling/index",
      },
      collapsed: false,
      label: "Tooling",
      items: [
        {
          type: "category",
          label: "clio",
          link: {
            type: "doc",
            id: "api-reference/tooling/clio/index",
          },
          items: [
            {
              type: "category",
              label: "Command Reference",
              link: {
                type: "doc",
                id: "api-reference/tooling/clio/command-reference/index",
              },
              items: [
                {
                  type: "category",
                  label: "convert",
                  link: {
                    type: "doc",
                    id: "api-reference/tooling/clio/command-reference/convert/index",
                  },
                  items: [
                    "api-reference/tooling/clio/command-reference/convert/pack-action-data",
                    "api-reference/tooling/clio/command-reference/convert/pack-transaction",
                    "api-reference/tooling/clio/command-reference/convert/unpack-action-data",
                    "api-reference/tooling/clio/command-reference/convert/unpack-transaction",
                  ],
                },
                {
                  type: "category",
                  label: "create",
                  link: {
                    type: "doc",
                    id: "api-reference/tooling/clio/command-reference/create/index",
                  },
                  items: [
                    "api-reference/tooling/clio/command-reference/create/account",
                    "api-reference/tooling/clio/command-reference/create/key",
                  ],
                },
                {
                  type: "category",
                  label: "get",
                  link: {
                    type: "doc",
                    id: "api-reference/tooling/clio/command-reference/get/index",
                  },
                  items: [
                    "api-reference/tooling/clio/command-reference/get/abi",
                    "api-reference/tooling/clio/command-reference/get/account",
                    "api-reference/tooling/clio/command-reference/get/block",
                    "api-reference/tooling/clio/command-reference/get/code",
                    "api-reference/tooling/clio/command-reference/get/currency-balance",
                    "api-reference/tooling/clio/command-reference/get/currency-stats",
                    "api-reference/tooling/clio/command-reference/get/info",
                    "api-reference/tooling/clio/command-reference/get/schedule",
                    "api-reference/tooling/clio/command-reference/get/scope",
                    "api-reference/tooling/clio/command-reference/get/table",
                    "api-reference/tooling/clio/command-reference/get/transaction-status",
                    "api-reference/tooling/clio/command-reference/get/transaction_trace",
                    "api-reference/tooling/clio/command-reference/get/block_trace",
                    "api-reference/tooling/clio/command-reference/get/deprecated/transaction_id",
                    "api-reference/tooling/clio/command-reference/get/deprecated/transaction",
                    "api-reference/tooling/clio/command-reference/get/deprecated/servants",
                    "api-reference/tooling/clio/command-reference/get/deprecated/accounts",
                  ],
                },
                {
                  type: "category",
                  label: "multisig",
                  link: {
                    type: "doc",
                    id: "api-reference/tooling/clio/command-reference/multisig/index",
                  },
                  items: [
                    "api-reference/tooling/clio/command-reference/multisig/multisig-approve",
                    "api-reference/tooling/clio/command-reference/multisig/multisig-cancel",
                    "api-reference/tooling/clio/command-reference/multisig/multisig-exec",
                    "api-reference/tooling/clio/command-reference/multisig/multisig-invalidate",
                    "api-reference/tooling/clio/command-reference/multisig/multisig-propose-trx",
                    "api-reference/tooling/clio/command-reference/multisig/multisig-propose",
                    "api-reference/tooling/clio/command-reference/multisig/multisig-review",
                    "api-reference/tooling/clio/command-reference/multisig/multisig-unapprove",
                  ],
                },
                {
                  type: "category",
                  label: "net",
                  link: {
                    type: "doc",
                    id: "api-reference/tooling/clio/command-reference/net/index",
                  },
                  items: [
                    "api-reference/tooling/clio/command-reference/net/connect",
                    "api-reference/tooling/clio/command-reference/net/disconnect",
                    "api-reference/tooling/clio/command-reference/net/peers",
                    "api-reference/tooling/clio/command-reference/net/status",
                  ],
                },
                {
                  type: "category",
                  label: "push",
                  link: {
                    type: "doc",
                    id: "api-reference/tooling/clio/command-reference/push/index",
                  },
                  items: [
                    "api-reference/tooling/clio/command-reference/push/push-action",
                    "api-reference/tooling/clio/command-reference/push/push-transaction",
                    "api-reference/tooling/clio/command-reference/push/push-transactions",
                  ],
                },
                {
                  type: "category",
                  label: "set",
                  link: {
                    type: "doc",
                    id: "api-reference/tooling/clio/command-reference/set/index",
                  },
                  items: [
                    "api-reference/tooling/clio/command-reference/set/set-abi",
                    "api-reference/tooling/clio/command-reference/set/set-account",
                    "api-reference/tooling/clio/command-reference/set/set-action",
                    "api-reference/tooling/clio/command-reference/set/set-code",
                    "api-reference/tooling/clio/command-reference/set/set-contract",
                  ],
                },
                {
                  type: "category",
                  label: "system",
                  link: {
                    type: "doc",
                    id: "api-reference/tooling/clio/command-reference/system/index",
                  },
                  items: [
                    "api-reference/tooling/clio/command-reference/system/system-bidname",
                    "api-reference/tooling/clio/command-reference/system/system-bidname",
                    "api-reference/tooling/clio/command-reference/system/system-bidnameinfo",
                    "api-reference/tooling/clio/command-reference/system/system-buyram",
                    "api-reference/tooling/clio/command-reference/system/system-canceldelay",
                    "api-reference/tooling/clio/command-reference/system/system-claimrewards",
                    "api-reference/tooling/clio/command-reference/system/system-delegatebw",
                    "api-reference/tooling/clio/command-reference/system/system-listbw",
                    "api-reference/tooling/clio/command-reference/system/system-listproducers",
                    "api-reference/tooling/clio/command-reference/system/system-newaccount",
                    "api-reference/tooling/clio/command-reference/system/system-regproducer",
                    "api-reference/tooling/clio/command-reference/system/system-regproxy",
                    // "api-reference/tooling/clio/command-reference/system/system-rex-buyrex",
                    // "api-reference/tooling/clio/command-reference/system/system-rex-cancelrexorder",
                    // "api-reference/tooling/clio/command-reference/system/system-rex-closerex",
                    // "api-reference/tooling/clio/command-reference/system/system-rex-consolidate",
                    // "api-reference/tooling/clio/command-reference/system/system-rex-defundcpuloan",
                    // "api-reference/tooling/clio/command-reference/system/system-rex-defundnetloan",
                    // "api-reference/tooling/clio/command-reference/system/system-rex-deposit",
                    // "api-reference/tooling/clio/command-reference/system/system-rex-fundcpuloan",
                    // "api-reference/tooling/clio/command-reference/system/system-rex-fundnetloan",
                    // "api-reference/tooling/clio/command-reference/system/system-rex-lendrex",
                    // "api-reference/tooling/clio/command-reference/system/system-rex-mvfromsavings",
                    // "api-reference/tooling/clio/command-reference/system/system-rex-mvtosavings",
                    // "api-reference/tooling/clio/command-reference/system/system-rex-rentcpu",
                    // "api-reference/tooling/clio/command-reference/system/system-rex-rentnet",
                    // "api-reference/tooling/clio/command-reference/system/system-rex-rexexec",
                    // "api-reference/tooling/clio/command-reference/system/system-rex-sellrex",
                    // "api-reference/tooling/clio/command-reference/system/system-rex-unstaketorex",
                    // "api-reference/tooling/clio/command-reference/system/system-rex-updaterex",
                    // "api-reference/tooling/clio/command-reference/system/system-rex-withdraw",
                    // "api-reference/tooling/clio/command-reference/system/system-rex",
                    "api-reference/tooling/clio/command-reference/system/system-sellram",
                    "api-reference/tooling/clio/command-reference/system/system-undelegatebw",
                    "api-reference/tooling/clio/command-reference/system/system-unregprod",
                    "api-reference/tooling/clio/command-reference/system/system-unregproxy",
                    {
                      type: "category",
                      label: "system voteproducer",
                      link: {
                        type: "doc",
                        id: "api-reference/tooling/clio/command-reference/system/system-voteproducer",
                      },
                      items: [
                        "api-reference/tooling/clio/command-reference/system/system-voteproducer-approve",
                        "api-reference/tooling/clio/command-reference/system/system-voteproducer-prods",
                        "api-reference/tooling/clio/command-reference/system/system-voteproducer-proxy",
                        "api-reference/tooling/clio/command-reference/system/system-voteproducer-unapprove",
                      ],
                    },
                  ],
                },
                {
                  type: "category",
                  label: "validate",
                  link: {
                    type: "doc",
                    id: "api-reference/tooling/clio/command-reference/validate/index",
                  },
                  items: [
                    "api-reference/tooling/clio/command-reference/validate/validate-signatures",
                  ],
                },
                {
                  type: "category",
                  label: "version",
                  link: {
                    type: "doc",
                    id: "api-reference/tooling/clio/command-reference/version/index",
                  },
                  items: [
                    "api-reference/tooling/clio/command-reference/version/client",
                  ],
                },
                {
                  type: "category",
                  label: "wallet",
                  link: {
                    type: "doc",
                    id: "api-reference/tooling/clio/command-reference/wallet/index",
                  },
                  items: [
                    "api-reference/tooling/clio/command-reference/wallet/create",
                    "api-reference/tooling/clio/command-reference/wallet/create-key",
                    "api-reference/tooling/clio/command-reference/wallet/import",
                    "api-reference/tooling/clio/command-reference/wallet/keys",
                    "api-reference/tooling/clio/command-reference/wallet/list",
                    "api-reference/tooling/clio/command-reference/wallet/lock",
                    "api-reference/tooling/clio/command-reference/wallet/lock-all",
                    "api-reference/tooling/clio/command-reference/wallet/open",
                    "api-reference/tooling/clio/command-reference/wallet/private-keys",
                    "api-reference/tooling/clio/command-reference/wallet/unlock",
                  ],
                },
                "api-reference/tooling/clio/command-reference/sign",
                "api-reference/tooling/clio/command-reference/transfer",
              ],
            },
            // {
            //   type: "category",
            //   label: "Guides",
            //   items: [
            //     "api-reference/tooling/clio/guides/clio-options",
            //     "api-reference/tooling/clio/guides/how-to-create-a-wallet",
            //     "api-reference/tooling/clio/guides/how-to-create-an-account",
            //     "api-reference/tooling/clio/guides/how-to-create-a-key-pair",
            //     "api-reference/tooling/clio/guides/how-to-import-a-key",
            //     "api-reference/tooling/clio/guides/how-to-list-all-key-pairs",
            //     "api-reference/tooling/clio/guides/how-to-submit-a-transaction",
            //     "api-reference/tooling/clio/guides/how-to-deploy-a-smart-contract",
            //     "api-reference/tooling/clio/guides/how-to-get-block-information",
            //   ],
            // },
          ],
        },
        {
          type: "category",
          label: "kiod",
          link: {
            type: "doc",
            id: "api-reference/tooling/kiod/index",
          },
          items: [
            "api-reference/tooling/kiod/usage",
            {
              type: "category",
              label: "Plugins",
              link: {
                type: "doc",
                id: "api-reference/tooling/kiod/plugins/index",
              },
              items: [
                "api-reference/tooling/kiod/plugins/wallet-api-plugin",
                "api-reference/tooling/kiod/plugins/wallet-plugin",
              ],
            },
            // "api-reference/tooling/kiod/security",
            "api-reference/tooling/kiod/wallet-specification",
            "api-reference/tooling/kiod/troubleshooting",
            "api-reference/tooling/kiod/faq",
          ],
        },
        {
          type: "category",
          label: "nodeop",
          link: {
            type: "doc",
            id: "api-reference/tooling/nodeop/index",
          },
          items: [
            "api-reference/tooling/nodeop/nodeop-apis",
            "api-reference/tooling/nodeop/nodeop-cli",
            {
              type: "category",
              label: "Concepts",
              link: {
                type: "doc",
                id: "api-reference/tooling/nodeop/concepts/index",
              },
              items: [
                "api-reference/tooling/nodeop/concepts/context-free-data",
                "api-reference/tooling/nodeop/concepts/storage-and-read-modes",
              ],
            },
            {
              type: "category",
              label: "Plugins",
              items: [
                // "api-reference/tooling/nodeop/plugins/block-producing-explained",
                "api-reference/tooling/nodeop/plugins/blockvault-client-plugin",
                "api-reference/tooling/nodeop/plugins/chain-api-plugin",
                "api-reference/tooling/nodeop/plugins/chain-plugin",
                "api-reference/tooling/nodeop/plugins/db-size-api-plugin",
                "api-reference/tooling/nodeop/plugins/history-api-plugin",
                "api-reference/tooling/nodeop/plugins/history-plugin",
                "api-reference/tooling/nodeop/plugins/http-plugin",
                "api-reference/tooling/nodeop/plugins/net-api-plugin",
                "api-reference/tooling/nodeop/plugins/net-plugin",
                "api-reference/tooling/nodeop/plugins/producer-api-plugin",
                "api-reference/tooling/nodeop/plugins/producer-plugin",
                "api-reference/tooling/nodeop/plugins/resource-monitor-plugin",
                "api-reference/tooling/nodeop/plugins/state-history-plugin",
                "api-reference/tooling/nodeop/plugins/trace-api-plugin",
              ],
            },
            {
              type: "category",
              label: "Logging",
              link: {
                type: "doc",
                id: "api-reference/tooling/nodeop/native-logging",
              },
              items: [],
            },
            "api-reference/tooling/nodeop/replays",
            {
              type: "category",
              label: "How-To",
              items: [
                "api-reference/tooling/nodeop/how-to/how-to-configure-state-storage",
                "api-reference/tooling/nodeop/how-to/how-to-create-snapshot-with-full-history",
                "api-reference/tooling/nodeop/how-to/how-to-fast-start-without-old-history",
                "api-reference/tooling/nodeop/how-to/how-to-generate-a-blocks.log",
                "api-reference/tooling/nodeop/how-to/how-to-generate-a-snapshot",
                "api-reference/tooling/nodeop/how-to/how-to-replay-from-a-blocks.log",
                "api-reference/tooling/nodeop/how-to/how-to-replay-from-a-snapshot",
                "api-reference/tooling/nodeop/how-to/how-to-replay-or-resync-with-full-history",
                "api-reference/tooling/nodeop/how-to/how-to-restore-snapshot-with-full-history",
              ],
            },
            "api-reference/tooling/nodeop/troubleshooting",
          ],
        },
        {
          type: "category",
          label: "Wire CDT",
          link: {
            type: "doc",
            id: "api-reference/tooling/cdt/index",
          },
          items: [
            {
              type: "category",
              label: "Features",
              items: ["api-reference/tooling/cdt/features/binary-extension"],
            },
            {
              type: "category",
              label: "Command Reference",
              link: {
                type: "doc",
                id: "api-reference/tooling/cdt/ref-index",
              },
              items: [
                "api-reference/tooling/cdt/cdt-init",
                "api-reference/tooling/cdt/cdt-ld",
                "api-reference/tooling/cdt/cdt-abidiff",
                "api-reference/tooling/cdt/cdt-cc",
                "api-reference/tooling/cdt/cdt-cpp",
              ],
            },
          ],
        },
        {
          type: "category",
          link: {
            type: "doc",
            id: "api-reference/system-contracts/index",
          },
          collapsed: true,
          label: "System Contracts",
          items: [
            "api-reference/system-contracts/contracts/sysio.bios",
            "api-reference/system-contracts/contracts/sysio.boot",
            "api-reference/system-contracts/contracts/sysio.msig",
            "api-reference/system-contracts/contracts/sysio.system",
            "api-reference/system-contracts/contracts/sysio.token",
            "api-reference/system-contracts/contracts/sysio.wrap",
            "api-reference/system-contracts/contracts/sysio.roa",
            "api-reference/system-contracts/build-and-deploy",
            // "api-reference/system-contracts/how-to-guides/how-to-buy-ram",
            // "api-reference/system-contracts/how-to-guides/how-to-stake",
            // "api-reference/system-contracts/how-to-guides/how-to-vote",
            // "api-reference/system-contracts/how-to-guides/upgrading-the-sysio.system-contract",
            // "api-reference/system-contracts/how-to-guides/how-to-use-sysio.wrap",
            "api-reference/system-contracts/how-to-guides/how-to-sign-a-multisig-transaction-with-sysio.msig",
          ],
        },
        // {
        //   type: "category",
        //   label: "Utilities",
        //   link: {
        //     type: "doc",
        //     id: "api-reference/tooling/utilities/index",
        //   },
        //   items: [
        //     "api-reference/tooling/utilities/sysio-blocklog",
        //     "api-reference/tooling/utilities/trace-api-util",
        //   ],
        // },
      ],
    },
  ],

  guidesReferenceSidebar: [
    {
      type: "category",
      link: {
        type: "generated-index",
      },
      collapsed: false,
      label: "Guides",
      items: [
        "guides/clio-options",
        "guides/how-to-create-a-wallet",
        "guides/how-to-create-an-account",
        "guides/how-to-create-a-key-pair",
        "guides/how-to-import-a-key",
        "guides/how-to-list-all-key-pairs",
        "guides/how-to-submit-a-transaction",
        "guides/how-to-deploy-a-smart-contract",
        "guides/how-to-get-block-information",
        "guides/how-to-get-account-information",
        "guides/hello-world-video-testnet",
        "guides/how-to-return-values-from-actions",
        "guides/working-with-different-action-return-types",
      ],
    },
  ],
};

export default sidebars;
